version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: hackathon
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hackathon
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  python-app:
    build: ./backend/python
    volumes:
      - ./backend/python:/app
    ports:
      - '8081:8081'
    command: python telegram_scraper.py
  frontend:
    build: ./frontend
    ports:
      - 4173:4173
    environment:
      VITE_BASE_API_URL: http://backend:8080
